apiVersion: v1
kind: Service
metadata:
  name: spire-server
  namespace: spire
spec:
  type: LoadBalancer
  ports:
    - name: grpc
      port: 8081
      targetPort: 8081
      protocol: TCP
    - name: health
      port: 8080
      targetPort: 8080 
  selector:
    app: spire-server