apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: spire-agent
  namespace: spire
  labels:
    app: spire-agent
spec:
  selector:
    matchLabels:
      app: spire-agent
  template:
    metadata:
      namespace: spire
      labels:
        app: spire-agent
    spec:
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: spire-agent
      initContainers:
        - name: init
          # This is a small image with wait-for-it, choose whatever image
          # you prefer that waits for a service to be up. This image is built
          # from https://github.com/lqhl/wait-for-it
          image: cgr.dev/chainguard/wait-for-it
          args: ["-t", "30", "192.168.0.158:8081"]
      containers:
        - name: spire-agent
          image: knoxuser/spire-agent:latest
          args: ["-c", "/config/agent.conf"]
          env:
          - name: JOIN_TOKEN
            value: ""
          volumeMounts:
            - name: spire-config
              mountPath: /config
              readOnly: true
            - name: spire-bundle
              mountPath: /spire/bundle
            - name: spire-data
              mountPath: /spire
              readOnly: false
          livenessProbe:
            httpGet:
              path: /live
              port: 9090
            failureThreshold: 2
            initialDelaySeconds: 15
            periodSeconds: 60
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 9090
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: spire-config
          configMap:
            name: spire-agent
        - name: spire-bundle
          configMap:
            name: spire-bundle
        - name: spire-data
          hostPath:
            path: /spire
            type: DirectoryOrCreate