apiVersion: v1
kind: Service
metadata:
  name: spire-agent
  namespace: spire
  labels:
    app: spire-agent
spec:
  ports:
  - name: health
    port: 9090
    targetPort: 9090
  - name: grpc
    port: 9091
    targetPort: 9091
  selector:
    app: spire-agent